GET "LIBHDR"
GET "coroutines"

GLOBAL $(
   C2PTR:502
$)

LET WORKER2(ARG) = VALOF
$( ARG := COWAIT(ARG+1)
   RESULTIS ARG+1
$)

LET WORKER1(ARG) = VALOF
$( LET C2 = C2PTR
   RESULTIS RESUMECO(C2, ARG)
$)

LET START() BE
$( LET C1 = 0
   LET C2 = 0
   LET V = 0
   INITCO()
   C2 := CREATECO(WORKER2, 5000)
   C2PTR := C2
   C1 := CREATECO(WORKER1, 5000)

   V := CALLCO(C1, 10)
   IF V NE 11 DO $( WRITES("RESUME CROSS FAIL 1") ; NEWLINE() ; STOP(911) $)

   IF DELETECO(C1)=FALSE DO $( WRITES("RESUME CROSS FAIL 2") ; NEWLINE() ; STOP(912) $)
   IF DELETECO(C2)=FALSE DO $( WRITES("RESUME CROSS FAIL 3") ; NEWLINE() ; STOP(913) $)

   WRITES("Resume cross ok")
   NEWLINE()
$)
