GET "LIBHDR"
GET "coroutines"

LET WORKER(ARG) = VALOF
$( ARG := COWAIT(ARG+1)
   RESULTIS ARG+1
$)

LET START() BE
$( LET C = 0
   LET V = 0
   INITCO()
   C := CREATECO(WORKER, 5000)

   V := CALLCO(C, 0)
   IF V NE 1 DO $( WRITES("DELETE FAIL 1") ; NEWLINE() ; STOP(911) $)

   V := CALLCO(C, 10)
   IF V=0 DO $( WRITES("DELETE FAIL 2") ; NEWLINE() ; STOP(912) $)

   IF DELETECO(C)=FALSE DO $( WRITES("DELETE FAIL 3") ; NEWLINE() ; STOP(913) $)
   WRITES("Delete ok")
   NEWLINE()
$)
